import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Viewport } from "next";
import "./globals.scss";
import LayoutClient from "@/components/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Social Net",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export const viewport: Viewport = {
  themeColor: "#0e0b18",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
